name: light_dark_theme_toggle
description: "An animated, customizable Flutter widget for switching between light and dark modes with a visually appealing toggle."
version: 1.1.2
homepage: "https://vchib1.github.io/LightDarkThemeToggleWebApp/"
repository: "https://github.com/vchib1/LightDarkThemeToggle"
issue_tracker: "https://github.com/vchib1/LightDarkThemeToggle/issues"

topics:
  - theme-toggle
  - switch
  - toggle
  - widget
  - animation

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


