name: light_dark_theme_toggle
description: "The LightDarkThemeToggle widget is a customizable and animated light/dark theme toggle switch for Flutter apps. It provides a visually appealing way for users to switch between light and dark modes in your app."
version: 1.0.1
homepage: "https://github.com/vchib1/LightDarkThemeToggle"
repository: "https://github.com/vchib1/LightDarkThemeToggle"
issue_tracker: "https://github.com/vchib1/LightDarkThemeToggle/issues"

topics:
  - theme-toggle
  - switch
  - toggle
  - widget
  - animation

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


