name: light_dark_theme_toggle
description: "A Flutter package offering 8 pre-made animations using CustomPainter to smoothly transition between light and dark themes, perfect for creating dynamic theme switching effects."
version: 1.0.0
homepage: "https://github.com/vchib1/LightDarkThemeToggle"
repository: "https://github.com/vchib1/LightDarkThemeToggle"
issue_tracker: "https://github.com/vchib1/LightDarkThemeToggle/issues"

topics:
  - theme-toggle
  - switch
  - toggle
  - widget
  - animation

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


